import Head from 'next/head'

import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import Account from '../components/Account'
import Notes from '../components/UserNotes'

export default function Home() {
  const session = useSession()
  const supabase = useSupabaseClient()
  console.log(session)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto flex justify-center">
        <div className="flex w-full max-w-4xl items-center justify-center p-4">
          {!session ? (
            <div className="w-full">
              <Auth
                supabaseClient={supabase}
                appearance={{
                  theme: ThemeSupa,
                }}
                theme="default"
              />
            </div>
          ) : (
            <Notes />
          )}
        </div>
      </div>
    </>
  )
}
